### PR TITLE
Fix sources files resolution

### LINKED ISSUE #30: Source map URL should be resolved relative to resource (bis ;)
Hi,

Previous issue : #10

Something is still missing: the `*.map` files are correctly resolved to be relative to the minified file, but the `*.src` files are not resolved relative to their sourcemap files (they are resolved relative to the current directory, and end up 404ing).

### PR DESCRIPTION
**Pull request by arcanis**
Fixes #30

### CODE REVIEW

**Comment by arcanis** [comment]
@eriwen What do you think about this? I see two cases of tests that are breaking:

The what?-style, where both output seem to be equal, but the assertion fails
```
        ✗ supports inline source maps
	Expected eval()@test.js:6:10 to equal eval()@test.js:6:10.
	callback@/home/travis/build/stacktracejs/stacktrace-gps/spec/stacktrace-gps-spec.js:204:1
```

The which-is-the-valid-one?-style, where both outputs are equally correct
```
        ✗ retrieves source mapped location for function declarations
	Expected bar()@http://localhost:9999/test.js:2:9 to equal bar()@test.js:2:9.
	callback@/home/travis/build/stacktracejs/stacktrace-gps/spec/stacktrace-gps-spec.js:269:1
```

Do you want me to fix the test for the second fail category to pass? In the meantime, I'll check for the first one.

**Comment by arcanis** [comment]
I suspect the first category of bug to come from the fact that the current StackFrame version used for the test (0.3) is incompatible with the one used by the library. Not 100% sure, I can't run the tests on my computer.

**Comment by eriwen** [comment]
I'm sorry that the test output isn't as useful as it should be in this case.

I can reproduce the same conditions as CI here (master passes, pr/31 fails in the same way). I can investigate more this evening.

Can I ask why you're not able to run tests locally? I want to make sure that it's easy for contributors to do this, and it's important that we consider adding new tests here because this has been a source of pain for awhile.

**Comment by arcanis** [comment]
I've had to experiment a bit, but I've been able to run the tests :) Basically, the CONTRIBUTING.md was a bit out-of-date (`gulp test` instead of `make test`), I've had to install the [libicu52](http://packages.ubuntu.com/trusty/amd64/libicu52/download) package, and add `captureConsole: true` to get some logs. At some point the `gulp pr` wasn't running, but now it seems to work fine too, I'm not sure what changed (it might have been an issue with my DISPLAY environment).

I've fixed the issue that was raised about non-matching StackFrame instance, and now only the only fails remaining are due to the `http://localhost:9999/test.js` vs `test.js` conflict.

File: stacktrace-gps.js [hunk 1]
```diff
@@ -243,14 +251,24 @@
...
-                        sourceMappingURL = fileName.substring(0, fileName.lastIndexOf('/') + 1) + sourceMappingURL;
+                        sourceMappingURL = base + sourceMappingURL;
                     }
 
                     this._get(sourceMappingURL).then(function (map) {
                         var lineNumber = stackframe.lineNumber;
                         var columnNumber = stackframe.columnNumber;
+
+                        if (typeof map === 'string') {
+                            map = _parseJson(map.replace(/^\)\]\}'/, ''));
```
Comment (eriwen) [inline stacktrace-gps.js]: What's the need for running `map.replace()` here? When would one encounter such a beginning of a line (literally `)]}'`)?

**Comment by eriwen** [comment]
I'm glad you got the tests working - sorry it was more difficult than it should've been.

Other than my one concern, I think this PR is solid except that we need to change the fileNames in the few failing specs to have the full URL instead of just the relative path.

File: stacktrace-gps.js (hunk 1 above)
Comment (arcanis) [inline stacktrace-gps.js]: I used this construct because that's how the source-map module is currently parsing the data (cf [here](https://github.com/mozilla/source-map/blob/master/lib/source-map-consumer.js#L16-L18)). As to why they do this, it's quite probably to give the user a way to secure themselves against [JSON hijacking](http://stackoverflow.com/questions/2669690/why-does-google-prepend-while1-to-their-json-responses?lq=1).

**Comment by arcanis** [comment]
No problem! I've fixed the tests, so now everything pass  :white_check_mark:

**Comment by arcanis** [comment]
@eriwen I've seen that you've released a new version of stacktrace.js, but it doesn't yet ship this fix. Any idea when it will be released "in the wild"?

**Comment by eriwen** [comment]
I'm so sorry we totally spaced this. We'll get this into another release very soon (within the next week).

**Comment by eriwen** [comment]
@arcanis stacktrace-js v1.0.3 has been published including stacktrace-gps 2.4.0.

**Comment by arcanis** [comment]
That's great, thanks! :)

**Comment by arcanis** [comment]
@eriwen Actually, I fear that the dependencies haven't been updated in your last release - I checked the [stacktrace-with-promises-and-json-polyfills.min.js](https://github.com/stacktracejs/stacktrace.js/blob/master/dist/stacktrace-with-promises-and-json-polyfills.min.js) file, and the fix doesn't seem to be there:

```js
void (this.getMappedLocation = function(e) {
    return new Promise(function(t, n) {
        i(),
        s(e);
        var r = this.sourceCache
          , o = e.fileName;
        this._get(o).then(function(i) {
            var s = a(i)
              , c = "data:" === s.substr(0, 5);
            "/" === s[0] || c || (s = o.substring(0, o.lastIndexOf("/") + 1) + s),
            this._get(s).then(function(n) {
                var o = e.lineNumber
                  , i = e.columnNumber;
                t(u(n, e.args, o, i, r))
            }, n)["catch"](n)
        }
        .bind(this), n)["catch"](n)
    }
    .bind(this))
}
```

**Comment by eriwen** [comment]
You're right. stacktrace-gps v2.4.0 dist/ did not include the changes (though the sources did). stacktrace-gps 2.4.1 and stacktrace-js 1.0.4 fix this. 

I have verified that the `sourceRoot` option seems to exist in the `getMappedLocation` function. 

Sorry for the trouble here.
